<?php

function multianchor_permission() {
  return array(
    'edit multianchors' => array(
      'title' => t('Edit MultiAnchors'),
    ),
  );
}

function multianchor_menu() {

  $items = array();

  $items['admin/config/search/multianchor'] = array(
    'title' => 'Multianchor',
    'description' => 'Configure the multianchor',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('multianchor_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('edit multianchors'),
  );

  return $items;
}

function multianchor_settings() {
  $header = array(
    t('Url number'),
    t('Anchor number'),
    t('Total anchor weight'),
  );

  $rows = array(get_stat());

  // Вывод статистики
  $form['stat'] = array(
    '#type' => 'markup',
    '#markup'=>  theme('table', array('header' => $header, 'rows' => $rows)),
  );

  $form['urls'] = array(
    '#title' =>  t('Specify a set of URLs'),
    '#description' => t('URLs should be separated by commas'),
    '#type' => 'textarea',
    '#rows' => '25',
    '#default_value' => variable_get('multianchors'),
  );

  $form['caption'] = array(
    '#title' =>  t('Caption'),
    '#type' => 'textfield',
    '#default_value' => variable_get('multianchors_caption'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save settings'),
  );

  $form['hint'] = array(
    '#markup' =>
      '<p>
          # - link in the site <br>
          // - comment <br>
          | - separates the anchor of title <br>
          : - separates the title of weight <br>
          <br>'

  );

  $form['example'] = array(
    '#type' => 'fieldset',
    '#title' => 'Example',
    '#description' =>
     '<p><i>
          // comment<br>
          # http://3w-site.ru<br>
          first anchor | description : 50<br>
          second anchor | description : 30<br>
          <br>
           # http://3w-software.ru // comment<br>
          first anchor | description : 10<br>
          second anchor | description : 20<br>
          </i>
      </p>',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  return $form;
}

function get_stat() {
  $url = variable_get('multianchors');
  $anchors = parse_cache($url, $stat);
  return $stat;
}

function multianchor_theme() {
  return array(
    'multianchor_output' => array(
      'arguments' => array('result' => NULL),
    ),
  );
}

function theme_multianchor_output($cfg) {
  if (!empty($cfg['caption']))
    $output = $cfg['link'] . '<em></em>' . '<b>' . $cfg['caption'] . '</b>';
  else
    $output = '<em></em>' . $cfg['link'];
  return $output;
}

// Проверка формы на правильность введенных данных
function multianchor_settings_validate($form, &$form_state) {
  $ret = TRUE;
  $url_str = $form_state['values']['urls'];
  $lines = split("\n", $url_str);
  foreach ($lines as $index=>$l) {
    trim($l);

    if (ereg("//", $l) && !ereg("://", $l)) {
      $urls_array = split("//", $l, 2);
      $l=trim($urls_array[0]);
    }

    if (preg_match("/^[[:space:]]*$/", $l))
    continue;


    if ($l['0']=="#"){
      $urls_array = split("#", $l, 2);
      $key=trim($urls_array[1]);
      if (!preg_match("/\b(?:(?:https?|ftp):\/\/|www\.)[-a-z0-9+&@#\/%?=~_|!:,.;]*[-a-z0-9+&@#\/%=~_|]/i",$key)) {
        form_set_error('key', $index+1 . ' строка: Неккоректный URL адрес: ' . $key);
        $ret = FALSE;
        break;
      }
      continue;
    }

    if (!ereg('\|', $l)) {
      form_set_error('l',  $index+1 . ' строка: Отсутствует "|" в строке: ' . $l);
      $ret = FALSE;
      break;
    }

    if (!ereg(':', $l)) {
      form_set_error('l',  $index+1 . ' строка: Отсутствует ":" в строке: ' . $l);
      $ret = FALSE;
      break;
    }
    $str_array = explode(":", $l, 2);
    if (!preg_match("/^[0-9]+$/",  trim($str_array[1]))) {
      form_set_error('trim($str_array[1])', $index+1 . ' строка: Коэффициент должен быть целым числом: ' . trim($str_array[1]));
      $ret = FALSE;
      break;
    }

  }

  return $ret;
}

// Сохранение всех введенных анкоров
function multianchor_settings_submit($form, &$form_state) {
  $urlStr = $form_state['values']['urls'];
  $caption = $form_state['values']['caption'];
  variable_set('multianchors', $urlStr);
  variable_set('multianchors_caption', $caption);
  $anchors = parse_cache($urlStr);

  cache_set("cache_anchors", $anchors, "cache_block" , CACHE_PERMANENT);
  cache_clear_all(NULL, 'cache_page');
}



function multianchor_block_info() {
  $blocks = array();
  $blocks[0]['info'] = t('MultiAnchor');
  $blocks[0]['cache'] = DRUPAL_CACHE_PER_PAGE;
  $blocks[0]['status'] = 1;
  $blocks[0]['region'] = 'footer';

  return $blocks;
}

// Вывод в блок
function multianchor_block_view($delta = '') {
  $caption = variable_get('multianchors_caption');

  if ( arg(0) == 'node' && is_numeric(arg(1)) && ! arg(2)) {
    $node = node_load(arg(1));
    $link = anchor($node->nid);
  } else {
    $link = anchor(crc32(arg(0) . arg(1) . arg(2))) ;
  }

  $blocks = array();
  $blocks['subject'] = null;
  $cfg= array('caption' => check_plain($caption), 'link'=>$link);
  $blocks['content'] = theme('multianchor_output', $cfg);
  return $blocks;
}


// Рулетка
function generate_anchor($anchors, $seed) {
  $num_sectors = 0;
    foreach ($anchors as $anchor) {
      foreach($anchor as $a) {
          $num_sectors += $a['points'];
      }
    }
  srand($seed);
  $sector = rand(1, $num_sectors);

    foreach ($anchors as $link=>$anchor) {
      foreach($anchor as $a) {
          if ($sector <= $a['points']) return array("title" =>$a['title'],  "link" => $link, "label" => $a['anchor']);
            else $sector -= $a['points'];
      }
    }
}

function anchor($seed) {
  $anchors = cache_get("cache_anchors", "cache_block");
    if (empty($anchors->data)) {
      $urlStr = variable_get('multianchors');
      $anchors = parse_cache($urlStr);
      cache_set("cache_anchors", $anchors, "cache_block" , CACHE_PERMANENT);
      $anchors = cache_get("cache_anchors", "cache_block");
    }
  $anchor = generate_anchor($anchors->data, $seed);
  $title = $anchor["title"];
  $link = $anchor["link"];

  $label = $anchor["label"];
  $output = l($label, $link,  array('attributes' => array('title' => $title)));
  return $output;
}

function parse_cache($url_str, &$stats) {
  $lines = preg_split("/\n/", $url_str);
  $group=0;
  $index=0;
  $ratio=0;
  foreach ($lines as $l) {
    trim($l);
    if (preg_match("/\/\//", $l) && !preg_match("/:\/\//", $l)) {
      $urls_array = explode("//", $l, 2);
      $l=trim($urls_array[0]);
    }
    if (preg_match("/^[[:space:]]*$/", $l))
      continue;
    if ($l['0']=="#") {
      $urls_array = explode("#", $l, 2);
      $key=trim($urls_array[1]);
      $group++;
      continue;
    }

    $str_array = explode("|", $l, 2);
    $anchors[$key][$index]['anchor'] = trim($str_array[0]);
    $str_t_point = trim($str_array[1]);
    $str_array = explode(":", $str_t_point, 2);
    $anchors[$key][$index]['title'] = trim($str_array[0]);
    $anchors[$key][$index]['points'] = trim($str_array[1]);
    $index++;
    $ratio+=trim($str_array[1]);
  }
  $stats = array($group, $index, $ratio);

  return $anchors;
}
